package homeioexample


rule "B Lights Motion On"
    when
        $light : Item( name == "B_Lights_1", state == OFF)

        $itemState : ItemStateChangedEvent( name == "B_Motion_Detector", newState == OPEN )
    then
        System.out.println( "IncQuery droolsbundle: " + drools.getRule().getName());
        
        openhab.postCommand($light, ON);
end


rule "B Lights Motion Off"
    when
        $light : Item( name == "B_Lights_1", state == ON)

        $itemState : ItemStateChangedEvent( name == "B_Motion_Detector", newState == CLOSED)
    then
        System.out.println( "IncQuery droolsbundle: " + drools.getRule().getName());
        
        openhab.postCommand($light, OFF);
end