<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smarthome" nsURI="http://www.example.org/smarthome" nsPrefix="smarthome">
  <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartHome">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//ItemBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ItemBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" lowerBound="1"
        upperBound="-1" eType="#//Command" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
        upperBound="-1" eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchItem" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//SwitchState"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContactItem" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//ContactState"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//SwitchState.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContactState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ContactState.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass12"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnectionType">
    <eLiterals name="StateChange" literal="StateChange"/>
    <eLiterals name="Predicate" value="1" literal="Predicate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContactState">
    <eLiterals name="OPEN" literal="OPEN"/>
    <eLiterals name="CLOSED" value="1" literal="CLOSED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SwitchState">
    <eLiterals name="ON"/>
    <eLiterals name="OFF" value="1" literal="OFF"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionType" eType="#//ConnectionType"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//State"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1" eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimmerItem" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//PercentState"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PercentState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SwitchCommand">
    <eLiterals name="ON"/>
    <eLiterals name="OFF" value="1"/>
    <eLiterals name="CHANGE_STATE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchCommand" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="#//SwitchCommand"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1" eType="#//SwitchItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimmerCommand" abstract="true" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1" eType="#//DimmerItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimmerOnOffCommand" eSuperTypes="#//DimmerCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="#//SwitchCommand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimmerPercentCommand" eSuperTypes="#//DimmerCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
