package genrules

import org.eclipse.smarthome.core.items.Item;
import org.eclipse.smarthome.core.library.types.OnOffType;
import org.eclipse.smarthome.core.library.types.OpenClosedType;
import org.eclipse.smarthome.core.library.types.PercentType;
import org.eclipse.smarthome.core.library.types.DecimalType;
import org.eclipse.smarthome.core.library.types.IncreaseDecreaseType;
import org.eclipse.smarthome.core.types.Command;
import org.eclipse.smarthome.core.types.State;
import com.incquerylabs.smarthome.eventbus.api.IEventPublisher;
import com.incquerylabs.smarthome.eventbus.api.events.ItemCommandEvent;
import com.incquerylabs.smarthome.eventbus.api.events.ItemCommandHistory;
import com.incquerylabs.smarthome.eventbus.api.events.ItemStateChangedEvent;
import com.incquerylabs.smarthome.eventbus.api.events.ItemStateHistory;
import com.incquerylabs.smarthome.eventbus.ruleengine.droolshomeio.DimmerCommand;
import com.incquerylabs.smarthome.eventbus.ruleengine.droolshomeio.DateTime;
import com.incquerylabs.smarthome.eventbus.ruleengine.droolshomeio.InitStates;

global IEventPublisher openhab;
global OpenClosedType OPEN;
global OpenClosedType CLOSED;
global OnOffType ON;
global OnOffType OFF;
global PercentType HUNDRED;
global PercentType ZERO;
global IncreaseDecreaseType INCREASE;
global IncreaseDecreaseType DECREASE;
global OpenClosedType BRIGHTNESS; 
global OpenClosedType DARKNESS; 
global OpenClosedType MOTION;
global OpenClosedType NOMOTION;
global OpenClosedType DOOR_OPENED;
global OpenClosedType DOOR_CLOSED;
global OpenClosedType PRESSED;
global OpenClosedType RELEASED;

global OpenClosedType ARMED
global OpenClosedType DISARMED

declare ItemCommandEvent
    @role ( event )
end


declare ItemCommandHistory
    @role ( event )
end


declare ItemStateChangedEvent
    @role ( event )
end


declare ItemStateHistory
    @role ( event )
end


rule "Init"
    lock-on-active
    when
        InitStates()
    then
        openhab.postCommand("Example_Light", OFF);
        openhab.postCommand("A_Lights_Analog", ZERO); 
        
        openhab.postCommand("gLight", OFF);
        openhab.postCommand("gRollerShadesUp", OFF);
        openhab.postCommand("gRollerShadesDown", OFF);
end


rule "Item command event"
    when
        $itemCommand : ItemCommandEvent( name : name, command : command)
    then
        System.out.println( "IncQuery droolsbundle: " + $itemCommand);
end


rule "Item state changed event"
    when
        $itemState : ItemStateChangedEvent( $item : item, name : name, newState : newState, oldState : oldState)
    then
        System.out.println( "IncQuery droolsbundle: item " + $itemState);
end