package homeioexample

rule "D Lights Switch Dimmer Up"
    when
        $item : Item( name == "D_Lights_1_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent( ( 
        name == "D_Light_Switch_Dimmer_1_Up" || 
        name == "D_Light_Switch_Dimmer_2_Up" ) && 
        newState == OPEN )

    then
        openhab.timedCommand(TimedDimmer.create($item, INCREASE, 2 , 1000, 50));
end


rule "D Lights Switch Dimmer Down"
    when
        $item : Item( name == "D_Lights_1_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent( ( 
        name == "D_Light_Switch_Dimmer_1_Down" || 
        name == "D_Light_Switch_Dimmer_2_Down" ) && 
        newState == OPEN )

    then
        openhab.timedCommand(TimedDimmer.create($item, DECREASE, 2 , 1000, 50));
end


rule "D Dimmer off"
    when
        $itemState : ItemStateChangedEvent( name matches "D_Light_Switch_Dimmer.*", newState == CLOSED )
    
    then
        openhab.stopTimedCommand("D_Lights_1_Analog");
end