package homeioexample

rule "H Lights Switch Dimmer Up"
    when
        $item : Item( name == "H_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent( 
        name == "H_Light_Switch_Dimmer_Up" && 
        newState == PRESSED )

    then
        openhab.startComplexCommand(DimmerCommand.create($item, INCREASE, 2 , 1000, 50));
end


rule "H Lights Switch Dimmer Down"
    when
        $item : Item( name == "H_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent(
        name == "H_Light_Switch_Dimmer_Down" && 
        newState == PRESSED )

    then
        openhab.startComplexCommand(DimmerCommand.create($item, DECREASE, 2 , 1000, 50));
end


rule "H Dimmer off"
    when
        $itemState : ItemStateChangedEvent( name matches "H_Light_Switch_Dimmer.*", newState == RELEASED )
    
    then
        openhab.stopComplexCommand("H_Lights_Analog");
end