package homeioexample

rule "J Lights Switch Dimmer Up"
    when
        $item : Item( name == "J_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent( 
        name == "J_Light_Switch_Dimmer_Up" && 
        newState == PRESSED )

    then
        openhab.timedCommand(TimedDimmer.create($item, INCREASE, 2 , 1000, 50));
end


rule "J Lights Switch Dimmer Down"
    when
        $item : Item( name == "J_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent(
        name == "J_Light_Switch_Dimmer_Down" && 
        newState == PRESSED )

    then
        openhab.timedCommand(TimedDimmer.create($item, DECREASE, 2 , 1000, 50));
end


rule "J Dimmer off"
    when
        $itemState : ItemStateChangedEvent( name matches "J_Light_Switch_Dimmer.*", newState == RELEASED )
    
    then
        openhab.stopTimedCommand("J_Lights_Analog");
end