package homeioexample
/*
rule "A Lights Switch Dimmer Up"
    when
        $item : Item( name == "A_Lights_Analog" ) 

        $itemStateOpen : ItemStateChangedEvent( ( 
        name == "A_Light_Switch_Dimmer_1_Up" || 
        name == "A_Light_Switch_Dimmer_2_Up" || 
        name == "A_Light_Switch_Dimmer_3_Up") && 
        newState == OPEN )

    then
        openhab.timedCommand(TimedDimmer.create($item, INCREASE, 2 , 1000, 50));
end


rule "A Lights Switch Dimmer Down"
    when
        $item : Item( name == "A_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent( ( 
        name == "A_Light_Switch_Dimmer_1_Down" || 
        name == "A_Light_Switch_Dimmer_2_Down" || 
        name == "A_Light_Switch_Dimmer_3_Down") && 
        newState == OPEN )

    then
        openhab.timedCommand(TimedDimmer.create($item, DECREASE, 2 , 1000, 50));
end



rule "A Dimmer off"
    when
        $itemState : ItemStateChangedEvent($name : name matches "A_Light_Switch_Dimmer.*", newState == CLOSED )
    
    then
        openhab.stopTimedCommand("A_Lights_Analog");
end

*/