package homeioexample

rule "E Lights Switch Dimmer Up"
    when
        $item : Item( name == "E_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent( ( 
        name == "E_Light_Switch_Dimmer_1_Up" || 
        name == "E_Light_Switch_Dimmer_2_Up" ) && 
        newState == OPEN )

    then
        openhab.timedCommand(TimedDimmer.create($item, INCREASE, 2 , 1000, 50));
end


rule "E Lights Switch Dimmer Down"
    when
        $item : Item( name == "E_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent( ( 
        name == "E_Light_Switch_Dimmer_1_Down" || 
        name == "E_Light_Switch_Dimmer_2_Down" ) && 
        newState == OPEN )

    then
        openhab.timedCommand(TimedDimmer.create($item, DECREASE, 2 , 1000, 50));
end


rule "E Dimmer off"
    when
        $itemState : ItemStateChangedEvent( name matches "E_Light_Switch_Dimmer.*", newState == CLOSED )
    
    then
        openhab.stopTimedCommand("E_Lights_Analog");
end