package homeioexample

rule "L Lights Switch Dimmer Up"
    when
        $item : Item( name == "L_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent( ( 
        name == "L_Light_Switch_Dimmer_1_Up" || 
        name == "L_Light_Switch_Dimmer_2_Up" ) && 
        newState == PRESSED )

    then
        openhab.startComplexCommand(DimmerCommand.create($item, INCREASE, 2 , 1000, 50));
end


rule "L Lights Switch Dimmer Down"
    when
        $item : Item( name == "L_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateChangedEvent( ( 
        name == "L_Light_Switch_Dimmer_1_Down" || 
        name == "L_Light_Switch_Dimmer_2_Down" ) && 
        newState == PRESSED )

    then
        openhab.startComplexCommand(DimmerCommand.create($item, DECREASE, 2 , 1000, 50));
end


rule "L Dimmer off"
    when
        $itemState : ItemStateChangedEvent( name matches "L_Light_Switch_Dimmer.*", newState == RELEASED )
    
    then
        openhab.stopComplexCommand("L_Lights_Analog");
end