package homeioexample


rule "D Lights Motion"
    when
        $light : Item( name == "D_Lights_1_Analog", $lightState : state)
        $brigthnessSensor : Item( name == "D_Brightness_Sensor", $brightnesSesnsorState: state)

        $itemState : ItemStateChangedEvent( name == "D_Motion_Detector", $motionDetectorState : newState)
    then
        System.out.println( "IncQuery droolsbundle: " + drools.getRule().getName());
        
        if (!$lightState.equals(ZERO) && $motionDetectorState == CLOSED) {
            //openhab.postCommand($light, ZERO);
        } else if ($lightState.equals(ZERO) && $motionDetectorState == OPEN && $brightnesSesnsorState == OPEN) {
            openhab.postCommand($light, HUNDRED);
            openhab.postCommand("D_Lights_2", ON);
        }
end