package homeioexample


rule "B lights 1"
    when
        $item : Item( name == "B_Lights_1", $state : state)

        $itemState : ItemStateChangedEvent( name == "B_Light_Switch_1", newState == OPEN)
    then
        System.out.println( "IncQuery droolsbundle: " + drools.getRule().getName());
        if ($state == ON) {
            openhab.postCommand($item, OFF);
        } else {
            openhab.postCommand($item, ON);
        }
end


rule "B lights 2"
    when
        $item : Item( name == "B_Lights_2", $state : state)

        $itemState : ItemStateChangedEvent( name == "B_Light_Switch_2", newState == OPEN)
    then
        System.out.println( "IncQuery droolsbundle: " + drools.getRule().getName());
        if ($state == ON) {
            openhab.postCommand($item, OFF);
        } else {
            openhab.postCommand($item, ON);
        }
end