package homeioexample


rule "A Lights Switch On"
    when
        $item : Item( name == "A_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateHistory( ( 
        name == "A_Light_Switch_Dimmer_1_Up" || 
        name == "A_Light_Switch_Dimmer_2_Up" || 
        name == "A_Light_Switch_Dimmer_3_Up") && 
        newState == OPEN )


        $itemStateClosed : ItemStateChangedEvent ( 
        this after[0s,1s] $itemStateOpen && 
        ( name == "A_Light_Switch_Dimmer_1_Up" || 
        name == "A_Light_Switch_Dimmer_2_Up" || 
        name == "A_Light_Switch_Dimmer_3_Up") && 
        newState == CLOSED )
    then
        System.out.println( "IncQuery droolsbundle: " + drools.getRule().getName());

        openhab.postCommand($item.getName(), HUNDRED);
end


rule "A Lights Switch Off"
    when
        $item : Item( name == "A_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateHistory( ( 
        name == "A_Light_Switch_Dimmer_1_Down" || 
        name == "A_Light_Switch_Dimmer_2_Down" || 
        name == "A_Light_Switch_Dimmer_3_Down") && 
        newState == OPEN )

        $itemStateClosed : ItemStateChangedEvent ( 
        this after[0s,1s] $itemStateOpen && 
        ( name == "A_Light_Switch_Dimmer_1_Down" || 
        name == "A_Light_Switch_Dimmer_2_Down" || 
        name == "A_Light_Switch_Dimmer_3_Down") && 
        newState == CLOSED )
    then
        System.out.println( "IncQuery droolsbundle: " + drools.getRule().getName());

        openhab.postCommand($item.getName(), ZERO);
end


rule "A Outdoor lights 1"
    when
        $item : Item( name == "O_Lights_Porch_1", $state : state)

        $itemState : ItemStateChangedEvent( name == "A_Light_Switch_1", newState == OPEN)
    then
        System.out.println( "IncQuery droolsbundle: " + drools.getRule().getName());
        if ($state == ON) {
            openhab.postCommand($item, OFF);
        } else {
            openhab.postCommand($item, ON);
        }
end


rule "A Outdoor lights 2"
    when
        $item : Item( name == "O_Lights_Porch_2", $state : state)

        $itemState : ItemStateChangedEvent( name == "A_Light_Switch_2", newState == OPEN)
    then
        System.out.println( "IncQuery droolsbundle: " + drools.getRule().getName());
        if ($state == ON) {
            openhab.postCommand($item, OFF);
            openhab.postCommand("O_Lights_Pool", OFF);
        } else {
            openhab.postCommand($item, ON);
            openhab.postCommand("O_Lights_Pool", ON);
        }
end