package homeioexample


rule "I Lights Switch"
    when
        $light : Item( name == "I_Lights_1_Analog", $state : state)

        ItemStateChangedEvent( name == "I_Light_Switch", newState == PRESSED)
    then
        if ($state.equals(HUNDRED)) {
            openhab.postCommand($light, OFF);
        } else {
            openhab.postCommand($light, ON);
        }
end


rule "I Lights Switch On"
    when
        $light : Item( name == "I_Lights_2_Analog", $state : state) 

        $switchPressed : ItemStateHistory(  
        name == "I_Light_Switch_Dimmer_Up"  && 
        newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && 
        name == "I_Light_Switch_Dimmer_Up" && 
        newState == RELEASED )
    then
        openhab.postCommand($light, ON);
end


rule "I Lights Switch Off"
    when
        $light : Item( name == "I_Lights_2_Analog", $state : state) 

        $switchPressed : ItemStateHistory(  
        name == "I_Light_Switch_Dimmer_Down"  && 
        newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && 
        name == "I_Light_Switch_Dimmer_Down" && 
        newState == RELEASED )
    then
        openhab.postCommand($light, OFF);
end