package homeioexample


rule "G Lights Switch"
    when
        $item : Item( name == "G_Lights_Analog", $state : state)

        $itemState : ItemStateChangedEvent( ( 
        name == "G_Light_Switch_1"||
        name == "G_Light_Switch_2"||
        name == "G_Light_Switch_3"||
        name == "G_Light_Switch_4"||
        name == "G_Light_Switch_5") &&
         newState == OPEN)
    then
        if ($state.equals(HUNDRED)) {
            openhab.postCommand($item, OFF);
        } else {
            openhab.postCommand($item, ON);
        }
end