package homeioexample


rule "L Lights Switch"
    when
        $item : Item( name == "L_Lights_Analog", $state : state)

        $itemState : ItemStateChangedEvent( name == "L_Light_Switch_1", newState == OPEN)
    then
        if ($state.equals(HUNDRED)) {
            openhab.postCommand($item, OFF);
        } else {
            openhab.postCommand($item, ON);
        }
end

rule "L Lights Switch On"
    when
        $item : Item( name == "L_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateHistory( ( 
        name == "L_Light_Switch_Dimmer_1_Up" || 
        name == "L_Light_Switch_Dimmer_2_Up" ) && 
        newState == OPEN )


        $itemStateClosed : ItemStateChangedEvent ( 
        this after[0s,1s] $itemStateOpen && (
        name == "L_Light_Switch_Dimmer_1_Up" || 
        name == "L_Light_Switch_Dimmer_2_Up" ) && 
        newState == CLOSED )
    then
        openhab.postCommand($item, ON);
end


rule "L Lights Switch Off"
    when
        $item : Item( name == "L_Lights_Analog", $state : state) 

        $itemStateOpen : ItemStateHistory( ( 
        name == "L_Light_Switch_Dimmer_1_Down" || 
        name == "L_Light_Switch_Dimmer_2_Down" ) && 
        newState == OPEN )

        $itemStateClosed : ItemStateChangedEvent ( 
        this after[0s,1s] $itemStateOpen && (
        name == "L_Light_Switch_Dimmer_1_Down" || 
        name == "L_Light_Switch_Dimmer_2_Down" ) && 
        newState == CLOSED )
    then
        openhab.postCommand($item, OFF);
end