package homeioexample


rule "I Lights Switch"
    when
        $item : Item( name == "I_Lights_1_Analog", $state : state)

        $itemState : ItemStateChangedEvent( name == "I_Light_Switch", newState == OPEN)
    then
        if ($state.equals(HUNDRED)) {
            openhab.postCommand($item, OFF);
        } else {
            openhab.postCommand($item, ON);
        }
end


rule "I Lights Switch On"
    when
        $item : Item( name == "I_Lights_2_Analog", $state : state) 

        $itemStateOpen : ItemStateHistory(  
        name == "I_Light_Switch_Dimmer_Up"  && 
        newState == OPEN )


        $itemStateClosed : ItemStateChangedEvent ( 
        this after[0s,1s] $itemStateOpen && 
        name == "I_Light_Switch_Dimmer_Up" && 
        newState == CLOSED )
    then
        openhab.postCommand($item, ON);
end


rule "I Lights Switch Off"
    when
        $item : Item( name == "I_Lights_2_Analog", $state : state) 

        $itemStateOpen : ItemStateHistory(  
        name == "I_Light_Switch_Dimmer_Down"  && 
        newState == OPEN )

        $itemStateClosed : ItemStateChangedEvent ( 
        this after[0s,1s] $itemStateOpen && 
        name == "I_Light_Switch_Dimmer_Down" && 
        newState == CLOSED )
    then
        openhab.postCommand($item, OFF);
end