package homeioexample


rule "K Lights Switch"
    when
        $light : Item( name == "K_Lights_Analog", $state : state)

        ItemStateChangedEvent( name == "L_Light_Switch_2", newState == PRESSED)
    then
        if ($state.equals(HUNDRED)) {
            openhab.postCommand($light, OFF);
        } else {
            openhab.postCommand($light, ON);
        }
end


rule "K Lights Switch On"
    when
        $light : Item( name == "K_Lights_Analog") 

        $switchPressed : ItemStateHistory(name == "K_Light_Switch_Dimmer_Up", newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed &&
        name == "K_Light_Switch_Dimmer_Up" && 
        newState == RELEASED )
    then
        openhab.postCommand($light, ON);
end


rule "K Lights Switch Off"
    when
        $light : Item( name == "K_Lights_Analog") 

        $switchPressed : ItemStateHistory(name == "K_Light_Switch_Dimmer_Down", newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed &&
        name == "K_Light_Switch_Dimmer_Down" && 
        newState == RELEASED )
    then
        openhab.postCommand($light, OFF);
end