package homeioexample


rule "N Lights Switch"
    when
        $light1 : Item( name == "N_Lights_1_Analog", $state : state)
        $light2 : Item( name == "N_Lights_2_Analog")
        $light3 : Item( name == "N_Lights_3_Analog")


        $itemState : ItemStateChangedEvent( (
        name == "N_Light_Switch_1" || 
        name == "N_Light_Switch_2" || 
        name == "N_Light_Switch_3") && 
        newState == PRESSED)
        
    then
        if ($state.equals(HUNDRED)) {
            openhab.postCommand($light1, OFF);
            openhab.postCommand($light2, OFF);
            openhab.postCommand($light3, OFF);
        } else {
            openhab.postCommand($light1, ON);
            openhab.postCommand($light2, ON);
            openhab.postCommand($light3, ON);
        }
end

rule "N Lights Switch On"
    when
        $light1 : Item( name == "N_Lights_1_Analog", $state : state)
        $light2 : Item( name == "N_Lights_2_Analog")
        $light3 : Item( name == "N_Lights_3_Analog")

        $switchPressed : ItemStateHistory( ( 
        name == "N_Light_Switch_Dimmer_1_Up" || 
        name == "N_Light_Switch_Dimmer_2_Up" || 
        name == "N_Light_Switch_Dimmer_3_Up" ) && 
        newState == PRESSED )


        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && (
        name == "N_Light_Switch_Dimmer_1_Up" || 
        name == "N_Light_Switch_Dimmer_2_Up" || 
        name == "N_Light_Switch_Dimmer_3_Up" ) && 
        newState == RELEASED )
    then
        openhab.postCommand($light1, ON);
        openhab.postCommand($light2, ON);
        openhab.postCommand($light3, ON);
end


rule "N Lights Switch Off"
    when
        $light1 : Item( name == "N_Lights_1_Analog", $state : state)
        $light2 : Item( name == "N_Lights_2_Analog")
        $light3 : Item( name == "N_Lights_3_Analog")

        $switchPressed : ItemStateHistory( ( 
        name == "N_Light_Switch_Dimmer_1_Down" || 
        name == "N_Light_Switch_Dimmer_2_Down" ||
        name == "N_Light_Switch_Dimmer_3_Down" ) && 
        newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && (
        name == "N_Light_Switch_Dimmer_1_Down" || 
        name == "N_Light_Switch_Dimmer_2_Down" ||
        name == "N_Light_Switch_Dimmer_3_Down" ) && 
        newState == RELEASED )
    then
        openhab.postCommand($light1, OFF);
        openhab.postCommand($light2, OFF);
        openhab.postCommand($light3, OFF);
end