package homeioexample


rule "D Lights Switch On"
    when
        $item : Item( name == "D_Lights_1_Analog", $state : state) 

        $itemStateOpen : ItemStateHistory( ( 
        name == "D_Light_Switch_Dimmer_1_Up" || 
        name == "D_Light_Switch_Dimmer_2_Up" ) && 
        newState == OPEN )


        $itemStateClosed : ItemStateChangedEvent ( 
        this after[0s,1s] $itemStateOpen && (
        name == "D_Light_Switch_Dimmer_1_Up" || 
        name == "D_Light_Switch_Dimmer_2_Up" ) && 
        newState == CLOSED )
    then
        openhab.postCommand($item.getName(), ON);
end


rule "D Lights Switch Off"
    when
        $item : Item( name == "D_Lights_1_Analog", $state : state) 

        $itemStateOpen : ItemStateHistory( ( 
        name == "D_Light_Switch_Dimmer_1_Down" || 
        name == "D_Light_Switch_Dimmer_2_Down" ) && 
        newState == OPEN )

        $itemStateClosed : ItemStateChangedEvent ( 
        this after[0s,1s] $itemStateOpen && (
        name == "D_Light_Switch_Dimmer_1_Down" || 
        name == "D_Light_Switch_Dimmer_2_Down" ) && 
        newState == CLOSED )
    then
        openhab.postCommand($item.getName(), OFF);
end


rule "D corridor lights"
    when
        $item : Item( name == "D_Lights_2", $state : state)

        $itemState : ItemStateChangedEvent( ( name == "A_Light_Switch_3" || name == "E_Light_Switch_2" ) && newState == OPEN)
    then
        if ($state == ON) {
            openhab.postCommand($item, OFF);
        } else {
            openhab.postCommand($item, ON);
        }
end