package homeioexample


rule "B lights 1"
    when
        $light : Item( name == "B_Lights_1", $state : state)

        ItemStateChangedEvent( name == "B_Light_Switch_1", newState == PRESSED)
    then
        if ($state == ON) {
            openhab.postCommand($light, OFF);
        } else {
            openhab.postCommand($light, ON);
        }
end


rule "B lights 2"
    when
        $light : Item( name == "B_Lights_2", $state : state)

        ItemStateChangedEvent( name == "B_Light_Switch_2", newState == PRESSED)
    then
        if ($state == ON) {
            openhab.postCommand($light, OFF);
        } else {
            openhab.postCommand($light, ON);
        }
end