package homeioexample


rule "D Lights Switch On"
    when
        $light : Item( name == "D_Lights_1_Analog") 

        $switchPressed : ItemStateChangedHistory( ( 
        name == "D_Light_Switch_Dimmer_1_Up" || 
        name == "D_Light_Switch_Dimmer_2_Up" ) && 
        newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && (
        name == "D_Light_Switch_Dimmer_1_Up" || 
        name == "D_Light_Switch_Dimmer_2_Up" ) && 
        newState == RELEASED )
    then
        openhab.postCommand($light, ON);
end


rule "D Lights Switch Off"
    when
        $light : Item( name == "D_Lights_1_Analog") 

        $switchPressed : ItemStateChangedHistory( ( 
        name == "D_Light_Switch_Dimmer_1_Down" || 
        name == "D_Light_Switch_Dimmer_2_Down" ) && 
        newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && (
        name == "D_Light_Switch_Dimmer_1_Down" || 
        name == "D_Light_Switch_Dimmer_2_Down" ) && 
        newState == RELEASED )
    then
        openhab.postCommand($light, OFF);
end


rule "D corridor lights"
    when
        $light : Item( name == "D_Lights_2_Analog", $state : state)

        ItemStateChangedEvent( ( name == "A_Light_Switch_3" || name == "E_Light_Switch_2" ) && newState == OPEN)
    then
        if ($state.equals(HUNDRED)) {
            openhab.postCommand($light, OFF);
        } else {
            openhab.postCommand($light, ON);
        }
end