package homeioexample


rule "E Lights Switch"
    when
        $light1 : Item( name == "E_Lights_Analog", $state1 : state)
        $light2 : Item( name == "G_Lights_Analog")

        ItemStateChangedEvent( name == "E_Light_Switch_1", newState == OPEN)
    then
        if ($state1.equals(HUNDRED)) {
            openhab.postCommand($light1, OFF);
            openhab.postCommand($light2, OFF);
        } else {
            openhab.postCommand($light1, ON);
            openhab.postCommand($light2, ON);
        }
end


rule "E Lights Switch On"
    when
        $light : Item( name == "E_Lights_Analog") 

        $switchPressed : ItemStateChangedHistory( ( 
        name == "E_Light_Switch_Dimmer_1_Up" || 
        name == "E_Light_Switch_Dimmer_2_Up" ) && 
        newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && (
        name == "E_Light_Switch_Dimmer_1_Up" || 
        name == "E_Light_Switch_Dimmer_2_Up" ) && 
        newState == RELEASED )
    then
        openhab.postCommand($light, ON);
end


rule "E Lights Switch Off"
    when
        $light : Item( name == "E_Lights_Analog") 

        $switchPressed : ItemStateChangedHistory( ( 
        name == "E_Light_Switch_Dimmer_1_Down" || 
        name == "E_Light_Switch_Dimmer_2_Down" ) && 
        newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && (
        name == "E_Light_Switch_Dimmer_1_Down" || 
        name == "E_Light_Switch_Dimmer_2_Down" ) && 
        newState == RELEASED )
    then
        openhab.postCommand($light, OFF);
end