package homeioexample


rule "G Lights Switch"
    when
        $light : Item( name == "G_Lights_Analog", $state : state)

        ItemStateChangedEvent( ( 
        name == "G_Light_Switch_1"||
        name == "G_Light_Switch_2"||
        name == "G_Light_Switch_3"||
        name == "G_Light_Switch_4"||
        name == "G_Light_Switch_5") &&
         newState == PRESSED)
    then
        if ($state.equals(HUNDRED)) {
            openhab.postCommand($light, OFF);
        } else {
            openhab.postCommand($light, ON);
        }
end