package homeioexample


rule "A Lights Switch On"
    when
        $light : Item( name == "A_Lights_Analog") 

        $switchPressed : ItemStateHistory( ( 
        name == "A_Light_Switch_Dimmer_1_Up" || 
        name == "A_Light_Switch_Dimmer_2_Up" || 
        name == "A_Light_Switch_Dimmer_3_Up") && 
        newState == PRESSED )


        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && 
        ( name == "A_Light_Switch_Dimmer_1_Up" || 
        name == "A_Light_Switch_Dimmer_2_Up" || 
        name == "A_Light_Switch_Dimmer_3_Up") && 
        newState == RELEASED )
    then
        openhab.postCommand($light, ON);
end


rule "A Lights Switch Off"
    when
        $light : Item( name == "A_Lights_Analog") 

        $switchPressed : ItemStateHistory( ( 
        name == "A_Light_Switch_Dimmer_1_Down" || 
        name == "A_Light_Switch_Dimmer_2_Down" || 
        name == "A_Light_Switch_Dimmer_3_Down") && 
        newState == PRESSED )

        ItemStateChangedEvent ( 
        this after[0s,1s] $switchPressed && 
        ( name == "A_Light_Switch_Dimmer_1_Down" || 
        name == "A_Light_Switch_Dimmer_2_Down" || 
        name == "A_Light_Switch_Dimmer_3_Down") && 
        newState == RELEASED )
    then

        openhab.postCommand($light, OFF);
end


rule "A Outdoor lights 1"
    when
        $light : Item( name == "O_Lights_Porch_1", $state : state)

        ItemStateChangedEvent( name == "A_Light_Switch_1", newState == PRESSED)
    then
        if ($state == ON) {
            openhab.postCommand($light, OFF);
        } else {
            openhab.postCommand($light, ON);
        }
end


rule "A Outdoor lights 2"
    when
        $light1 : Item( name == "O_Lights_Porch_2", $state1 : state)
        $light2 : Item( name == "O_Lights_Pool", $state2 : state)

        ItemStateChangedEvent( name == "A_Light_Switch_2", newState == PRESSED)
    then
        if ($state1 == ON && $state2 == ON) {
            openhab.postCommand($light1, OFF);
            openhab.postCommand($light2, OFF);
        } else {
            openhab.postCommand($light1, ON);
            openhab.postCommand($light2, ON);
        }
end