package homeioexample


rule "J Lights Motion"
    when
        $light : Item( name == "J_Lights_Analog", $lightState : state)
        Item( name == "J_Brightness_Sensor", $brightnessSensorState: state)

        ItemStateChangedEvent( name == "J_Motion_Detector", $motionDetectorState : newState)
    then
        if ($lightState.equals(ZERO) && $motionDetectorState == MOTION && $brightnessSensorState == DARKNESS) {
            openhab.postCommand($light, ON);
        }
end