package homeioexample


rule "H Lights Motion"
    when
        $light : Item( name == "H_Lights_Analog", $lightState : state)
        Item( name == "H_Brightness_Sensor", $brightnessSensorState: state)

        ItemStateChangedEvent( name == "H_Motion_Detector", $motionDetectorState : newState)
    then
        if ($lightState.equals(ZERO) && $motionDetectorState == MOTION && $brightnessSensorState == DARKNESS) {
            openhab.postCommand($light, ON);
        }
end