package homeioexample


rule "D Lights Motion"
    when
        $light : Item( name == "D_Lights_1_Analog", $lightState : state)
        Item( name == "D_Brightness_Sensor", $brightnessSensorState: state)

        ItemStateChangedEvent( name == "D_Motion_Detector", $motionDetectorState : newState)
    then
        if ($lightState.equals(ZERO) && $motionDetectorState == MOTION && $brightnessSensorState == DARKNESS) {
            openhab.postCommand($light, ON);
            openhab.postCommand("D_Lights_2", ON);
        }
end