package homeioexample


rule "F Lights Motion"
    when
        $light : Item( name == "F_Lights_Analog", $lightState : state)
        Item( name == "F_Brightness_Sensor", $brightnessSensorState: state)

        ItemStateChangedEvent( name == "F_Motion_Detector", $motionDetectorState : newState)
    then
        if ($lightState.equals(ZERO) && $motionDetectorState == MOTION && $brightnessSensorState == DARKNESS) {
            openhab.postCommand($light, ON);
        }
end
