package homeioexample


rule "N Lights Motion"
    when
        $item1 : Item( name == "N_Lights_3_Analog", $lightState : state)
        $item2 : Item( name == "N_Lights_2_Analog")
        $item3 : Item( name == "N_Lights_1_Analog")
        Item( name == "N_Brightness_Sensor", $brightnessSensorState: state)

        ItemStateChangedEvent( name == "N_Motion_Detector", $motionDetectorState : newState)
    then
        if ($lightState.equals(ZERO) && $motionDetectorState == MOTION && $brightnessSensorState == DARKNESS) {
            openhab.postCommand($item1, ON);
            openhab.postCommand($item2, ON);
            openhab.postCommand($item3, ON);
        }
end