package homeioexample


rule "I Lights Motion 1"
    when
        $light : Item( name == "I_Lights_1_Analog", state == ZERO)

        ItemStateChangedEvent( name == "I_Motion_Detector", newState == MOTION)
    then
        openhab.postCommand($light, ON);
end


rule "I Lights Motion 2"
    when
        $light : Item( name == "I_Lights_2_Analog", state == ZERO)

        ItemStateChangedEvent( name == "I_Motion_Detector", newState == MOTION)
    then
        openhab.postCommand($light, ON);
end