package homeioexample


rule "A Lights Motion"
    when
        $light : Item( name == "A_Lights_Analog", $lightState : state)
        Item( name == "A_Brightness_Sensor", $brightnessSensorState: state)

        ItemStateChangedEvent( name == "A_Motion_Detector", $motionDetectorState : newState)
    then
        if ($lightState.equals(ZERO) && $motionDetectorState == MOTION && $brightnessSensorState == DARKNESS) {
            openhab.postCommand($light, HUNDRED);
        }
end