package homeioexample


rule "G roller shades up switch"
    when
        $upMotor : Item( name == "G_Roller_Shades_Up", state == OFF)
        $downMotor : Item( name == "G_Roller_Shades_Down", $stateDown : state) 

        $itemState : ItemStateChangedEvent( name == "G_Up_Down_Switch_Up", newState == OPEN )
    then
        if ( $stateDown == OFF ) {
        	openhab.postCommand($upMotor, ON);
        } else {
            openhab.postCommand($downMotor, OFF);
        }
end
		
		
rule "G RollerShades down switch"
    when
        $upMotor : Item( name == "G_Roller_Shades_Up", $stateUp : state)
        $downMotor : Item( name == "G_Roller_Shades_Down", state == OFF) 

        $itemState : ItemStateChangedEvent( name == "G_Up_Down_Switch_Down", newState == OPEN )
    then
        if( $stateUp == OFF) {
            openhab.postCommand($downMotor, ON);
        } else {
            openhab.postCommand($upMotor, OFF);
        }
end


rule "G roller shades up off"
	when
		$upMotor : Item( name == "G_Roller_Shades_Up", state == ON)
		
		ItemStateChangedEvent( name == "G_Roller_Shades_Openness", newState == HUNDRED )
	then
		openhab.postCommand($upMotor, OFF);
end


rule "G roller shades down off"
	when
		$downMotor : Item( name == "G_Roller_Shades_Down", state == ON) 
		
		ItemStateChangedEvent( name == "G_Roller_Shades_Openness", newState == ZERO)
	then
		openhab.postCommand($downMotor, OFF);
end