package homeioexample


rule "L RollerShades"
    when
        Item( name == "L_Roller_Shades_Up", $stateUp : state)
        Item( name == "L_Roller_Shades_Down", $stateDown : state) 

        $itemState : ItemStateChangedEvent( (
        name == "L_Up_Down_Switch_Up" || 
        name == "L_Up_Down_Switch_Down") && 
        newState == OPEN )
    then
        if($itemState.getName().equals("L_Up_Down_Switch_Up") ) {

            if( $stateUp == OFF && $stateDown == OFF) {
                openhab.postCommand("L_Roller_Shades_Up", ON);
            }
            else {
                openhab.postCommand("L_Roller_Shades_Down", OFF);
            }
        }
        else {

            if( $stateUp == OFF && $stateDown == OFF) {
                openhab.postCommand("L_Roller_Shades_Down", ON);
            }
            else {
                openhab.postCommand("L_Roller_Shades_Up", OFF);
            }
        }
end


rule "L roller shades up switch"
    when
        $upMotor : Item( name == "L_Roller_Shades_Up", state == OFF)
        $downMotor : Item( name == "L_Roller_Shades_Down", $stateDown : state) 

        $itemState : ItemStateChangedEvent( name == "L_Up_Down_Switch_Up", newState == OPEN )
    then
        if ( $stateDown == OFF ) {
        	openhab.postCommand($upMotor, ON);
        } else {
            openhab.postCommand($downMotor, OFF);
        }
end
		
		
rule "L RollerShades down switch"
    when
        $upMotor : Item( name == "L_Roller_Shades_Up", $stateUp : state)
        $downMotor : Item( name == "L_Roller_Shades_Down", state == OFF) 

        $itemState : ItemStateChangedEvent( name == "L_Up_Down_Switch_Down", newState == OPEN )
    then
        if( $stateUp == OFF) {
            openhab.postCommand($downMotor, ON);
        } else {
            openhab.postCommand($upMotor, OFF);
        }
end


rule "L roller shades up off"
	when
		$upMotor : Item( name == "L_Roller_Shades_Up", state == ON)
		
		ItemStateChangedEvent( name == "L_Roller_Shades_Openness", newState == HUNDRED )
	then
		openhab.postCommand($upMotor, OFF);
end


rule "L roller shades down off"
	when
		$downMotor : Item( name == "L_Roller_Shades_Down", state == ON) 
		
		ItemStateChangedEvent( name == "L_Roller_Shades_Openness", newState == ZERO)
	then
		openhab.postCommand($downMotor, OFF);
end