package homeioexample


rule "A roller shades 1 up switch"
    when
        $upMotor : Item( name == "A_Roller_Shades_1_Up", state == OFF)
        $downMotor : Item( name == "A_Roller_Shades_1_Down", $stateDown : state) 

        $itemState : ItemStateChangedEvent( name == "A_Up_Down_Switch_1_Up", newState == OPEN )
    then
        if ( $stateDown == OFF ) {
        	openhab.postCommand($upMotor, ON);
        } else {
            openhab.postCommand($downMotor, OFF);
        }
end
		
		
rule "A roller shades 2 up switch"
    when
        $upMotor : Item( name == "A_Roller_Shades_2_Up", state == OFF)
        $downMotor : Item( name == "A_Roller_Shades_2_Down", $stateDown : state) 

        $itemState : ItemStateChangedEvent( name == "A_Up_Down_Switch_1_Up", newState == OPEN )
    then
        if ( $stateDown == OFF ) {
        	openhab.postCommand($upMotor, ON);
        } else {
            openhab.postCommand($downMotor, OFF);
        }
end
		
		
rule "A roller shades 3 up switch"
    when
        $upMotor : Item( name == "A_Roller_Shades_3_Up", state == OFF)
        $downMotor : Item( name == "A_Roller_Shades_3_Down", $stateDown : state) 

        $itemState : ItemStateChangedEvent( name == "A_Up_Down_Switch_2_Up", newState == OPEN )
    then
        if ( $stateDown == OFF ) {
        	openhab.postCommand($upMotor, ON);
        } else {
            openhab.postCommand($downMotor, OFF);
        }
end
		
		
rule "A roller shades 4 up switch"
    when
        $upMotor : Item( name == "A_Roller_Shades_4_Up", state == OFF)
        $downMotor : Item( name == "A_Roller_Shades_4_Down", $stateDown : state) 

        $itemState : ItemStateChangedEvent( name == "A_Up_Down_Switch_2_Up", newState == OPEN )
    then
        if ( $stateDown == OFF ) {
        	openhab.postCommand($upMotor, ON);
        } else {
            openhab.postCommand($downMotor, OFF);
        }
end
		
		
rule "A RollerShades 1 down switch"
    when
        $upMotor : Item( name == "A_Roller_Shades_1_Up", $stateUp : state)
        $downMotor : Item( name == "A_Roller_Shades_1_Down", state == OFF) 

        $itemState : ItemStateChangedEvent( name == "A_Up_Down_Switch_1_Down", newState == OPEN )
    then
        if( $stateUp == OFF) {
            openhab.postCommand($downMotor, ON);
        } else {
            openhab.postCommand($upMotor, OFF);
        }
end


rule "A RollerShades 2 down switch"
    when
        $upMotor : Item( name == "A_Roller_Shades_2_Up", $stateUp : state)
        $downMotor : Item( name == "A_Roller_Shades_2_Down", state == OFF) 

        $itemState : ItemStateChangedEvent( name == "A_Up_Down_Switch_1_Down", newState == OPEN )
    then
        if( $stateUp == OFF) {
            openhab.postCommand($downMotor, ON);
        } else {
            openhab.postCommand($upMotor, OFF);
        }
end


rule "A RollerShades 3 down switch"
    when
        $upMotor : Item( name == "A_Roller_Shades_3_Up", $stateUp : state)
        $downMotor : Item( name == "A_Roller_Shades_3_Down", state == OFF) 

        $itemState : ItemStateChangedEvent( name == "A_Up_Down_Switch_2_Down", newState == OPEN )
    then
        if( $stateUp == OFF) {
            openhab.postCommand($downMotor, ON);
        } else {
            openhab.postCommand($upMotor, OFF);
        }
end


rule "A RollerShades 4 down switch"
    when
        $upMotor : Item( name == "A_Roller_Shades_4_Up", $stateUp : state)
        $downMotor : Item( name == "A_Roller_Shades_4_Down", state == OFF) 

        $itemState : ItemStateChangedEvent( name == "A_Up_Down_Switch_2_Down", newState == OPEN )
    then
        if( $stateUp == OFF) {
            openhab.postCommand($downMotor, ON);
        } else {
            openhab.postCommand($upMotor, OFF);
        }
end


rule "A roller shades 1 up off"
	when
		$upMotor : Item( name == "A_Roller_Shades_1_Up", state == ON)
		
		ItemStateChangedEvent( name == "A_Roller_Shades_1_Openness", newState == HUNDRED )
	then
		openhab.postCommand($upMotor, OFF);
end


rule "A roller shades 1 down off"
	when
		$downMotor : Item( name == "A_Roller_Shades_1_Down", state == ON) 
		
		ItemStateChangedEvent( name == "A_Roller_Shades_1_Openness", newState == ZERO)
	then
		openhab.postCommand($downMotor, OFF);
end


rule "A roller shades 2 up off"
	when
		$upMotor : Item( name == "A_Roller_Shades_2_Up", state == ON)
		
		ItemStateChangedEvent( name == "A_Roller_Shades_2_Openness", newState == HUNDRED )
	then
		openhab.postCommand($upMotor, OFF);
end


rule "A roller shades 2 down off"
	when
		$downMotor : Item( name == "A_Roller_Shades_2_Down", state == ON) 
		
		ItemStateChangedEvent( name == "A_Roller_Shades_2_Openness", newState == ZERO)
	then
		openhab.postCommand($downMotor, OFF);
end


rule "A roller shades 3 up off"
	when
		$upMotor : Item( name == "A_Roller_Shades_3_Up", state == ON)
		
		ItemStateChangedEvent( name == "A_Roller_Shades_3_Openness", newState == HUNDRED )
	then
		openhab.postCommand($upMotor, OFF);
end


rule "A roller shades 3 down off"
	when
		$downMotor : Item( name == "A_Roller_Shades_3_Down", state == ON) 
		
		ItemStateChangedEvent( name == "A_Roller_Shades_3_Openness", newState == ZERO)
	then
		openhab.postCommand($downMotor, OFF);
end


rule "A roller shades 4 up off"
	when
		$upMotor : Item( name == "A_Roller_Shades_4_Up", state == ON)
		
		ItemStateChangedEvent( name == "A_Roller_Shades_4_Openness", newState == HUNDRED )
	then
		openhab.postCommand($upMotor, OFF);
end


rule "A roller shades 4 down off"
	when
		$downMotor : Item( name == "A_Roller_Shades_4_Down", state == ON) 
		
		ItemStateChangedEvent( name == "A_Roller_Shades_4_Openness", newState == ZERO)
	then
		openhab.postCommand($downMotor, OFF);
end