package homeioexample


rule "M RollerShades"
    when
        Item( name == "M_Roller_Shades_Up", $stateUp : state)
        Item( name == "M_Roller_Shades_Down", $stateDown : state) 

        $itemState : ItemStateChangedEvent( (
        name == "M_Up_Down_Switch_Up" || 
        name == "M_Up_Down_Switch_Down") && 
        newState == OPEN )
    then
        if($itemState.getName().equals("M_Up_Down_Switch_Up") ) {

            if( $stateUp == OFF && $stateDown == OFF) {
                openhab.postCommand("M_Roller_Shades_Up", ON);
            }
            else {
                openhab.postCommand("M_Roller_Shades_Down", OFF);
            }
        }
        else {

            if( $stateUp == OFF && $stateDown == OFF) {
                openhab.postCommand("M_Roller_Shades_Down", ON);
            }
            else {
                openhab.postCommand("M_Roller_Shades_Up", OFF);
            }
        }
end