//created on: Jul 10, 2017
package com.incquery.iot.eventbusclient

rule "Your First Rule"
    when
        command : ItemReceivedCommand( itemName == ItemReceivedCommand.allowPirSwitch, command == ItemReceivedCommand.ON )
    then
        System.out.println("Drools: " + command.getItemName() + " received command: " + command.getCommand() );
        eventBusService.postCommand(ItemReceivedCommand.mqttSwitch, ItemReceivedCommand.ON);
end

